### ISSUE TITLE
A lot of requests for .htc files

### ISSUE THREAD

**Issue by vergilius** [TurbineCSS/Turbine#179]
Hello everybody :)

Ok, here is the issue (only in ie8-9 ofc):

I've got 2 sites with nearly the same code.
On the first one turbine works great, htc plugins are received from server as text/css with empty response body.

On the second one, I've got a lot of requests to htc plugins, and they are received as text/x-component, and site looks terrible (black corners, awful texts etc)
Maybe it;s server side problem?

If I turn javascript off in browser then there is no issue anymore.. but i need javascript !

So guys, if anyone had similar problem or at least know what produces this issue please respond.

Thanks! :)

**Comment by commi** [comment]
Hi,

the htc's are not needed anymore for ie>=8 for the most part.
i never had problems with them, so i would say it's the server config OR the website uses the wrong browser mode (ie7-mode, ie8-compatibility-mode), try to enforce the mode with the meta-tag that exist for that purpose.

i shall push a new version as soon is i find the time with my latest patches tu Turbine, that includes omitting the legacy-htc's if non-ie or ie>8 is detected (since htc's wont work in offline mode anyway, there is need to include them for all browsers)
